controllers:
  perceptive_controller:
    type: legged/PerceptiveController
  legged_controller:
    type: legged/LeggedController
  legged_cheater_controller:
    type: legged/LeggedCheaterController
  aliengo_controller:
    type: legged/AliengoController  